---
services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: tSCER8nfmCHV1ikv7zr4lmUAmACxiNnkXpEjYeFasjplmyLok3G119woCJc7uvcPPqoON8ve2anZQVVvYikZTVBF5B11QrN6tzMi3ajVSzDnst3vGqQTCjFtLgFP5VbHw2gBNXtd9gWDqvUjaHRU+i6pLGiL9guZWqhoKYKy6b7N4FhKzVL0eiKoNtE3+rZ/8CstxjKTq1++OXCSR4kapWZLSF51WStt5PX7ZzZiGgAF3K1V/FlY/t/aUwtIOHz/WPObx/xg/v+R0IrSXTUYI3oCaZnUHNtcczDH6Ke4QYcWlSVcxMbl5/X7nDf/nZ1JV0AFvwyinc1mV+6Y10JCBTbsnCDSjcK7bvlvkodAN5YTWPI5NjvX3N4U6iJ0BFS0ngsavWJn+r+aQszpnprRLDlk9rH1u8IBaV2GSLlPR6h1Jae6YhQ0FLbdTZqSzN6fSWn+QraENg/D5eYLPux/jf5Aau0egOSV5AICHrYJk7RPy/sTASowQ0kCVuhMMftZoxEHKpAs7s/4xsF3Vm0C4vyaBjqUXZlfnjr3S+Lr59k8buN3XK9XgF39ch/V9QiwuxGXM1uZT5UNgil0mqKylLY5KsXoC/bGxPLem5oPKKCaNrQUvCcYBnKfX2qCqGchIeBG+znjv7CqY2aAaZBoo0Bok4jy0KmVSE/FqPuDd8w=
  - secure: bnOomWJ0fjy6WnkGsFcsip44gGIN/ekzYn06LlO8OPQ1raEQmqu+LvD8nizpJRw4mYOv1BiAZiytBVHua+wAmchqUgM3PGN+lXPoGIpB5amv4KreJT+1NwVcu7mNCZpQXkEBdbxa50fbrPn6JumhRx4XDG81FGZeMfFk0BJyGn38RMdctVgV0qUY3WoCyKpQSVqOeqzeQhfj0VBtUzHwC5IjHF7JLSaWbged5DtkYm1f8ZNtz7LfcHVERhtTAYqcEDgXyQ2FpkNy2ygFF/mglHEJMYQQgQwGB+ILgv9BgHW8ve+mn+eLXasUNOnjoxe4xfBg28aVPKzQ+ojRinTcoPAvQ3ujy8ncG8VPHVYvU621BlOJc6Ycnl2hMJfz1roGSDGY3vzQBH3rVbM/WZAdjaNc54ClukYp0eqMxZkgzLwrdjcNjRgNGQtAI/Wxz3VooMdEITJcgDjPc3GpScgFumSZnfWYUPXQCM3/6/fsWdNinz8yrkSmIbfr9hdnnQyD2g1hDR18auEOGlAJ6mBJPtcn064ZWC2FTqCBNAQ2p3FvnlVYbP2iSDppv6FY4JoHkpXW+yjgDqP0jaIzq6wAja2MkIGiDlTU7qWaRNepMidBr4Bse5eF86YGmMxBCXfqjMMQ3XVEh3K4j7C1ICDF3zABNtBYzRLXx0iMAdCTF24=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
