services:
- docker
language: python
python: 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
env:
  global:
  - secure: X2ITzG67r72jV9rg0imRQmrKwuYcQXck8gec+AE/+M2ZaE+Urd6iPkRPc6gsKZSmCUD60rCjrTY7sJmMmtEcWj9Cd1J8pUgZK8AMrKhfYU+hqscdJELW9P9m3vZW6RySxnRFHG7WQyQNno8QWj95OzcAOz+Sd3lFcfs3MeTnLbVOh989UxeZuOnteEqv1FV9vCBkbcjykyQvEUF6Xt+2qIgkuh4k4jBJ2iA1J/oD95LgAOOUiqsIhWFp7dcp3r9xlnDQJhlWYEHaekEdREDiQau22iIITMey7JimY3VAv/IWUEb8dS+aVZFFe707RRebnvWaTmFPBJS2NBzg//Ho3oV9Jui9qNJd9PwPEJBu4iZdmEhvwa7+szhQ91X0BMAEDYXu9+X0h2CNwoHOmcn2TPF5N2U73bDd2pgzzh0AX/Pj1bjaRsinRjVhXor+9pAJRLMRiVOIgmtapHQxTek8zuSYRAkqdc/LZqtdjjFiXgf6jLmObVoHq1aOyuMxbH6HUsX4iXBbREY4ZUyjVO/RewmbAndgWK7ilYeyNi6jcnMwZ83YKtUNkpJZOXsdAfj0vKEjzHziBsnsrhTJQqVlCXlrZWc0fI6UAGOt+vFbyEYIFqFgeqHzHbhxF2/Ph9//dQF1+w8PG1eGM9wg34/dOAnTG5NwlgKD9+wHGMl+CkA=
  - secure: AKxT3x5XkmpwO+071SaWmnG2Rsi6QtucDUvNHtjP8WUVqR2NLxIqe8LdeueiNJvJukYb8SbHafKcj9DvfR8oMczIJECLmkRycAwdZ/45rRNMEFjtnLXy7OG7pTZE/G46igbALm+gK9W9tDmow8YHRz9ZNv8LGLIuu5DQChdgh1rYQITSFkWNHwdw0lXe9IeqLvM2dhnquWclb7tTafqIhimlTboaclGokpwpbWZSXHOUUiJEX6zODg6Zs41QpND73bUSt6+C2xKdtUEfZ2Gjh3jzLjpYpp+iEiaKmR2cJn4dJk43cVfG7JIqbaWnV9u+ICvpYWzQuAu4wMJ3iK3+FoiNeRpQ1f6ZU3nRCith8iIJ/QND9OXTlwo0icDy1zEjXnmsTcE3v+Fee+tbj1rn1n7uFf3Um2ZObVgOwpopalT5QEqDpXVY8ePfLASeR6kAlQk5E3sKpvwKS4XgobgptXx1ydhMF9HD0GVhNXDe2b0q2aSeIXhs/xh0h0/hkV09Yv9tJiJaSwbzOAbxv4/qnxA2xgpDI1nYFfEPFdhuvViVm7RbaLM4X484REbrv8zeXfv5kAbMgZUG28ImOhnPTz+VV7OvxWCe+Q08XtEBczYRjramgtyDotp000h0lirEmNdPIZcCOhYDFgcg/hL3/zVBinhcpGN9l1DeAP3rM4U=
install:
- pip install --upgrade pip
- pip install -r requirements-build.txt
- nb setup
script:
- nb push
